[build-system]
requires = ["setuptools >= 61.2", "pbr>=1.9"]
build-backend = "setuptools.build_meta"

[project]
name = "dbt-duckdb"
description = "The duckdb adapter plugin for dbt (data build tool)"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "Apache-2"}
authors = [
    {name = "Josh Wills", email = "joshwills+dbt@gmail.com"}
]
keywords = ["setup", "distutils"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "dbt-common>=1,<2",
    "dbt-adapters>=1,<2",
    "duckdb>=1.0.0",
    # add dbt-core to ensure backwards compatibility of installation, this is not a functional dependency
    "dbt-core>=1.8.0",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/jwills/dbt-duckdb"

[project.optional-dependencies]
glue = [
    "boto3",
    "mypy-boto3-glue",
]
md = [
    "duckdb==1.3.2",
]

[tool.setuptools.packages.find]
include = ["dbt", "dbt.*"]

[tool.setuptools.package-data]
"*" = ["*"]

[tool.uv.sources]
dbt-duckdb = { workspace = true }

[dependency-groups]
dev = [
    "dbt-duckdb",
]
